# Generated by Django 4.1.1 on 2022-10-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("phone", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField(max_length=1024)),
            ],
        ),
    ]
